x <- c(5,6,8,7,4,1,9)
x1 <- c("B","A","C")
x2 <- c(3,2,NA,1,4,5)
sort(x)
sort(x,decreasing = FALSE)
sort(x,decreasingg = TRUE)
sort(x1)
sort(x1,decreasing = TRUE)
sort(x2)
sort(x2,na.last = TRUE)
rev(sort(x))